sudo: false
language: node_js
node_js:
  - "lts/*"
  - "stable"

install:
  - yarn install --frozen-lockfile

script:
  - yarn workspace license-info-webpack-plugin lint 'src/**/*'
  - yarn workspace license-info-webpack-plugin test
  - yarn workspace license-info-webpack-plugin build
  - yarn workspace test-v4 jest

cache: yarn
